queue_rules:
  - name: edge-frontend
    queue_conditions:
      - base=master
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - check-success=Travis CI - Pull Request
      - label!=work in progress
      - label!=do not merge
    merge_conditions:
      - base=master
      - "#approved-reviews-by>=1"
    merge_method: rebase

pull_request_rules:
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request is now in conflicts. Could you fix it @{{author}}?
          🙏"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: warn stale after 15 days
    conditions:
      - base=master
      - -closed
      - updated-at<15 days ago
    actions:
      comment:
        message: "This pull request is now 15 days old. Please revisit. PR will be
          closed in 15 more days. @{{author}}"
      label:
        add:
          - stale warning
  - name: close stale pull request
    conditions:
      - base=master
      - -closed
      - updated-at<30 days ago
    actions:
      close:
        message: "This pull request looks stale. Feel free to reopen it if you think
          it's a mistake."
  - name: waiting for review
    conditions:
      - "#approved-reviews-by<1"
      - created-at<1 days ago
      - -draft
    actions:
      label:
        add:
          - waiting for review
  - name: remove waiting for review label if not needed
    conditions:
      - "#approved-reviews-by>=2"
    actions:
      label:
        remove:
          - waiting for review
  - name: add bug fix label
    conditions:
      - body~=(?m)^- \[[xX]\] Bug fix \(non-breaking change which fixes an issue\)
    actions:
      label:
        add:
          - bug fix
  - name: add new feature label
    conditions:
      - body~=(?m)^- \[[xX]\] New feature \(non-breaking change which adds functionality\)
    actions:
      label:
        add:
          - new feature
  - name: add documentation label
    conditions:
      - body~=(?m)^- \[[xX]\] Documentation update
    actions:
      label:
        add:
          - documentation
  - name: add test update label
    conditions:
      - body~=(?m)^- \[[xX]\] Tests update
    actions:
      label:
        add:
          - test update
  - name: remove bug fix label
    conditions:
      - body~=(?m)^- \[ \] Bug fix \(non-breaking change which fixes an issue\)
    actions:
      label:
        remove:
          - bug fix
  - name: remove new feature label
    conditions:
      - body~=(?m)^- \[ \] New feature \(non-breaking change which adds functionality\)
    actions:
      label:
        remove:
          - new feature
  - name: remove documentation label
    conditions:
      - body~=(?m)^- \[ \] Documentation update
    actions:
      label:
        remove:
          - documentation
  - name: remove test update label
    conditions:
      - body~=(?m)^- \[ \] Tests update
    actions:
      label:
        remove:
          - test update

  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
