name: Build and release
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "📎 Lint, test and build"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Running tests
        run: npm test

      - name: Run build
        run: npm run build
